=== LokiMidgard/nota/input/render/books/Regelwerke/Grundregeln/talente/talent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:bsp="http://nota.org/"
        targetNamespace="http://nota.org/"
        elementFormDefault="qualified">
  <element name="Talente">
    <complexType>
      <sequence>
        <element name="Talent"  maxOccurs="unbounded" minOccurs="0" >
          <complexType>
            <sequence>
              <element name="Probe">
                <complexType>
                  <sequence>
                    <choice maxOccurs="3" minOccurs="3">
                      <element name="Mut" />
                      <element name="Glück" />
                      <element name="Klugheit" />
                      <element name="Intuition" />
                      <element name="Gewandtheit" />
                      <element name="Feinmotorik" />
                      <element name="Sympathie" />
                      <element name="Einschüchterung" />
                      <element name="Stärke" />
                      <element name="Konstitution" />
                    </choice>
                  </sequence>
                </complexType>
              </element>
              <element name="Beschreibung"  type="string"/>
              <element name="Ableitungen" minOccurs="0" maxOccurs="1"  type="bsp:AbleitungsAuswahl">
              </element>
            </sequence>
            <attribute type="ID" name="Name"/>
            <attribute type="bsp:Kategorie" use="required" name="Kategorie"/>
            <attribute type="bsp:Komplexität" use="required" name="Komplexität"/>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>

  <simpleType name="Kategorie">
    <restriction base="string">
      <enumeration value="Geist"/>
      <enumeration value="Körper"/>
      <enumeration value="Geselchaft"/>
      <enumeration value="Kampf"/>
      <enumeration value="Wissen"/>
      <enumeration value="Handwerk"/>
    </restriction>
  </simpleType>

  <simpleType name="Komplexität">
    <restriction base="string">
      <pattern value="[A-K]"/>
    </restriction>
  </simpleType>

  <complexType name="AbleitungsAuswahl">
    <sequence>
      <choice maxOccurs="unbounded">
        <element ref="bsp:Ableitung"/>
        <element ref="bsp:Max"/>
      </choice>
    </sequence>
  </complexType>



  <element name="Ableitung">
    <complexType  >
      <attribute name="Name" type="IDREF" />
      <attribute name="Anzahl" type="int" />
    </complexType>
  </element>

  <element name="Max" >
    <complexType>
      <sequence>
        <choice maxOccurs="unbounded" minOccurs="1">
          <element ref="bsp:Ableitung"/>
          <element ref="bsp:Max"/>
        </choice>
      </sequence>
      <attribute name="Anzahl" type="int" default="1" use="optional" />
    </complexType>
  </element>

</schema>

=== LokiMidgard/nota/input/render/books/Regelwerke/Grundregeln/talente/talent.xml
template: 'template\talent.xslt'
title: "Talente"
---
<?xml version='1.0'?>
<!-- This file represents a fragment of a book store inventory database -->
<Talente  xmlns='http://nota.org/' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://nota.org/ talent.xsd">
  <Talent Name="Fechtwaffen" Komplexität="B" Kategorie="Kampf">
    <Probe>
      <Glück/>
      <Mut/>
      <Intuition/>
    </Probe>
    <Beschreibung>
      Test
    </Beschreibung>
    <Ableitungen>
      <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      <Max>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      </Max>
    </Ableitungen>
  </Talent>
  <Talent Name="Springen" Komplexität="B" Kategorie="Körper">
    <Probe>
      <Mut/>
      <Klugheit/>
      <Mut/>
    </Probe>
    <Beschreibung>
      Test
    </Beschreibung>
    <Ableitungen>
      <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      <Max>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      </Max>
    </Ableitungen>
  </Talent>
  
  <Talent Name="Springen" Komplexität="B" Kategorie="Körper">
    <Probe>
      <Mut/>
      <Klugheit/>
      <Mut/>
    </Probe>
    <Beschreibung>
      Test
    </Beschreibung>
    <Ableitungen>
      <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      <Max>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      </Max>
    </Ableitungen>
  </Talent>
  <Talent Name="Springen" Komplexität="B" Kategorie="Körper">
    <Probe>
      <Mut/>
      <Klugheit/>
      <Mut/>
    </Probe>
    <Beschreibung>
      Test
    </Beschreibung>
    <Ableitungen>
      <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      <Max>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      </Max>
    </Ableitungen>
  </Talent>
<Talent Name="Springen" Komplexität="B" Kategorie="Körper">
    <Probe>
      <Mut/>
      <Klugheit/>
      <Mut/>
    </Probe>
    <Beschreibung>
      Test
    </Beschreibung>
    <Ableitungen>
      <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      <Max>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      </Max>
    </Ableitungen>
  </Talent>
<Talent Name="Springen" Komplexität="B" Kategorie="Körper">
    <Probe>
      <Mut/>
      <Klugheit/>
      <Mut/>
    </Probe>
    <Beschreibung>
      Test
    </Beschreibung>
    <Ableitungen>
      <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      <Max>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
        <Ableitung Name="Fechtwaffen" Anzahl="3"/>
      </Max>
    </Ableitungen>
  </Talent>
</Talente>
