=== LokiMidgard/nota/input/misc/documents/source/ActionCards/XMLImport.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="XMLImport"
  targetNamespace="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd"
  elementFormDefault="qualified"
  xmlns="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd"
  xmlns:mstns="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  >
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Fonts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Font" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Regular" type="FontLocation" />
                    <xs:element name="Italic" type="FontLocation" minOccurs="0"/>
                    <xs:element name="Bold" type="FontLocation" minOccurs="0" />
                    <xs:element name="BoldItalic" type="FontLocation" minOccurs="0" />
                  </xs:all>
                  <xs:attribute name="FamilyName" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="UseSystemFallback" type="xs:boolean" default="true"/>
            <xs:attribute name="DefaultFont" type="xs:string" default="Verdana"/>
          </xs:complexType>
          <xs:unique name="FontUniqness">
            <xs:selector xpath="mstns:Font"/>
            <xs:field xpath="@FamilyName"/>
          </xs:unique>
        </xs:element>
        <xs:element name="FallbackFonts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Font" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="FamilyName" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="NotFoundCharacter" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="FamilyName" type="xs:string" use="required"/>
                  <xs:attribute name="SubstituteCharacter" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="FontUniqness2">
            <xs:selector xpath="mstns:Font"/>
            <xs:field xpath="@FamilyName"/>
          </xs:unique>
        </xs:element>
        <xs:element name="Templates">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Template" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded">
                    <xs:element name="Image" type="mstns:ImageElement" />
                    <xs:element name="Text" type="mstns:TextElement" />
                    <xs:element name="Rect" type="mstns:RectElement" />

                  </xs:choice>
                  <xs:attribute name="Context" type="xs:string" use="required"/>
                  <xs:attribute name="Width" type="mstns:Unit" use="required"/>
                  <xs:attribute name="Height" type="mstns:Unit" use="required"/>
                  <xs:attribute name="Xslt" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="DefaultLanguage" type="Language" use="required"/>
    </xs:complexType>
    <xs:key name="FontPK">
      <xs:selector xpath="mstns:Fonts/mstns:Font"/>
      <xs:field xpath="@FamilyName"/>
    </xs:key>
    <xs:keyref name="FontFK" refer="mstns:FontPK">
      <xs:selector xpath="mstns:FallbackFonts/mstns:Font"/>
      <xs:field xpath="@FamilyName"/>
    </xs:keyref>
  </xs:element>


  <xs:complexType name="FontLocation">
    <xs:attribute name="Path" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:simpleType name="FontStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Regular" />
      <xs:enumeration value="Bold" />
      <xs:enumeration value="Italic" />
      <xs:enumeration value="BoldItalic" />
      <xs:enumeration value="Underline" />
      <xs:enumeration value="Strikeout" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Alignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Near" />
      <xs:enumeration value="Center" />
      <xs:enumeration value="Far" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Unit">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+(\.[0-9]+)? ?(pt|mm|cm|in|pu)"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="BaseElement" abstract="true">

    <xs:attribute name="left" type="mstns:Unit" use="required"/>
    <xs:attribute name="top" type="mstns:Unit" use="required"/>
    <xs:attribute name="width" type="mstns:Unit" use="required"/>
    <xs:attribute name="height" type="mstns:Unit" use="required"/>

    <xs:attribute name="rotation" type="xs:float" default="0"/>
    <xs:attribute name="rotationOriginX" type="xs:float" default="0"/>
    <xs:attribute name="rotationOriginY" type="xs:float" default="0"/>

    <xs:attribute name="IsVisible" type="xs:boolean" default="true"/>
    <xs:attribute name="IsVisiblePath" type="xs:string"/>

    <xs:attribute name="ZPosition" type="xs:double" default="0"/>


  </xs:complexType>

  <xs:complexType name="TextElement">
    <xs:complexContent>
      <xs:extension base="BaseElement">
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="mstns:Paragraph"/>
          <xs:element name="ForEach" type="mstns:ForeEachParagraph" />
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="RectElement">
    <xs:complexContent>
      <xs:extension base="BaseElement">
        <xs:all>
          <xs:element name="Border" minOccurs="0" maxOccurs="1">
            <xs:complexType>
              <xs:attribute name="Color" type="color" use="required"/>
              <xs:attribute name="Thikness" type="xs:double" default="1"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="Fill" minOccurs="0" maxOccurs="1">
            <xs:complexType>
              <xs:choice>
                <xs:element ref="GradientFill"/>
                <xs:element ref="SolidFill"/>
              </xs:choice>
            </xs:complexType>
          </xs:element>
        </xs:all>

      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="color">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern  value="#[a-fA-F0-9]{8}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="AliceBlue"/>
          <xs:enumeration value="AntiqueWhite"/>
          <xs:enumeration value="Aqua"/>
          <xs:enumeration value="Aquamarine"/>
          <xs:enumeration value="Azure"/>
          <xs:enumeration value="Beige"/>
          <xs:enumeration value="Bisque"/>
          <xs:enumeration value="Black"/>
          <xs:enumeration value="BlanchedAlmond"/>
          <xs:enumeration value="Blue"/>
          <xs:enumeration value="BlueViolet"/>
          <xs:enumeration value="Brown"/>
          <xs:enumeration value="BurlyWood"/>
          <xs:enumeration value="CadetBlue"/>
          <xs:enumeration value="Chartreuse"/>
          <xs:enumeration value="Chocolate"/>
          <xs:enumeration value="Coral"/>
          <xs:enumeration value="CornflowerBlue"/>
          <xs:enumeration value="Cornsilk"/>
          <xs:enumeration value="Crimson"/>
          <xs:enumeration value="Cyan"/>
          <xs:enumeration value="DarkBlue"/>
          <xs:enumeration value="DarkCyan"/>
          <xs:enumeration value="DarkGoldenrod"/>
          <xs:enumeration value="DarkGray"/>
          <xs:enumeration value="DarkGreen"/>
          <xs:enumeration value="DarkKhaki"/>
          <xs:enumeration value="DarkMagenta"/>
          <xs:enumeration value="DarkOliveGreen"/>
          <xs:enumeration value="DarkOrange"/>
          <xs:enumeration value="DarkOrchid"/>
          <xs:enumeration value="DarkRed"/>
          <xs:enumeration value="DarkSalmon"/>
          <xs:enumeration value="DarkSeaGreen"/>
          <xs:enumeration value="DarkSlateBlue"/>
          <xs:enumeration value="DarkSlateGray"/>
          <xs:enumeration value="DarkTurquoise"/>
          <xs:enumeration value="DarkViolet"/>
          <xs:enumeration value="DeepPink"/>
          <xs:enumeration value="DeepSkyBlue"/>
          <xs:enumeration value="DimGray"/>
          <xs:enumeration value="DodgerBlue"/>
          <xs:enumeration value="Firebrick"/>
          <xs:enumeration value="FloralWhite"/>
          <xs:enumeration value="ForestGreen"/>
          <xs:enumeration value="Fuchsia"/>
          <xs:enumeration value="Gainsboro"/>
          <xs:enumeration value="GhostWhite"/>
          <xs:enumeration value="Gold"/>
          <xs:enumeration value="Goldenrod"/>
          <xs:enumeration value="Gray"/>
          <xs:enumeration value="Green"/>
          <xs:enumeration value="GreenYellow"/>
          <xs:enumeration value="Honeydew"/>
          <xs:enumeration value="HotPink"/>
          <xs:enumeration value="IndianRed"/>
          <xs:enumeration value="Indigo"/>
          <xs:enumeration value="Ivory"/>
          <xs:enumeration value="Khaki"/>
          <xs:enumeration value="Lavender"/>
          <xs:enumeration value="LavenderBlush"/>
          <xs:enumeration value="LawnGreen"/>
          <xs:enumeration value="LemonChiffon"/>
          <xs:enumeration value="LightBlue"/>
          <xs:enumeration value="LightCoral"/>
          <xs:enumeration value="LightCyan"/>
          <xs:enumeration value="LightGoldenrodYellow"/>
          <xs:enumeration value="LightGray"/>
          <xs:enumeration value="LightGreen"/>
          <xs:enumeration value="LightPink"/>
          <xs:enumeration value="LightSalmon"/>
          <xs:enumeration value="LightSeaGreen"/>
          <xs:enumeration value="LightSkyBlue"/>
          <xs:enumeration value="LightSlateGray"/>
          <xs:enumeration value="LightSteelBlue"/>
          <xs:enumeration value="LightYellow"/>
          <xs:enumeration value="Lime"/>
          <xs:enumeration value="LimeGreen"/>
          <xs:enumeration value="Linen"/>
          <xs:enumeration value="Magenta"/>
          <xs:enumeration value="Maroon"/>
          <xs:enumeration value="MediumAquamarine"/>
          <xs:enumeration value="MediumBlue"/>
          <xs:enumeration value="MediumOrchid"/>
          <xs:enumeration value="MediumPurple"/>
          <xs:enumeration value="MediumSeaGreen"/>
          <xs:enumeration value="MediumSlateBlue"/>
          <xs:enumeration value="MediumSpringGreen"/>
          <xs:enumeration value="MediumTurquoise"/>
          <xs:enumeration value="MediumVioletRed"/>
          <xs:enumeration value="MidnightBlue"/>
          <xs:enumeration value="MintCream"/>
          <xs:enumeration value="MistyRose"/>
          <xs:enumeration value="Moccasin"/>
          <xs:enumeration value="NavajoWhite"/>
          <xs:enumeration value="Navy"/>
          <xs:enumeration value="OldLace"/>
          <xs:enumeration value="Olive"/>
          <xs:enumeration value="OliveDrab"/>
          <xs:enumeration value="Orange"/>
          <xs:enumeration value="OrangeRed"/>
          <xs:enumeration value="Orchid"/>
          <xs:enumeration value="PaleGoldenrod"/>
          <xs:enumeration value="PaleGreen"/>
          <xs:enumeration value="PaleTurquoise"/>
          <xs:enumeration value="PaleVioletRed"/>
          <xs:enumeration value="PapayaWhip"/>
          <xs:enumeration value="PeachPuff"/>
          <xs:enumeration value="Peru"/>
          <xs:enumeration value="Pink"/>
          <xs:enumeration value="Plum"/>
          <xs:enumeration value="PowderBlue"/>
          <xs:enumeration value="Purple"/>
          <xs:enumeration value="Red"/>
          <xs:enumeration value="RosyBrown"/>
          <xs:enumeration value="RoyalBlue"/>
          <xs:enumeration value="SaddleBrown"/>
          <xs:enumeration value="Salmon"/>
          <xs:enumeration value="SandyBrown"/>
          <xs:enumeration value="SeaGreen"/>
          <xs:enumeration value="SeaShell"/>
          <xs:enumeration value="Sienna"/>
          <xs:enumeration value="Silver"/>
          <xs:enumeration value="SkyBlue"/>
          <xs:enumeration value="SlateBlue"/>
          <xs:enumeration value="SlateGray"/>
          <xs:enumeration value="Snow"/>
          <xs:enumeration value="SpringGreen"/>
          <xs:enumeration value="SteelBlue"/>
          <xs:enumeration value="Tan"/>
          <xs:enumeration value="Teal"/>
          <xs:enumeration value="Thistle"/>
          <xs:enumeration value="Tomato"/>
          <xs:enumeration value="Transparent"/>
          <xs:enumeration value="Turquoise"/>
          <xs:enumeration value="Violet"/>
          <xs:enumeration value="Wheat"/>
          <xs:enumeration value="White"/>
          <xs:enumeration value="WhiteSmoke"/>
          <xs:enumeration value="Yellow"/>
          <xs:enumeration value="YellowGreen"/>
        </xs:restriction>

      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:complexType name="AbstractParagraph" abstract="true">
    <xs:attribute name="IsVisible" type="xs:boolean" default="true"/>
    <xs:attribute name="IsVisiblePath" type="xs:string"/>
  </xs:complexType>


  <xs:simpleType name="Language">
    <xs:restriction base="xs:string">
      <xs:enumeration value="de-DE"/>
      <xs:enumeration value="en-US"/>
      <xs:enumeration value="en-GB"/>
      <xs:enumeration value="ru-RU"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Fill">
  </xs:complexType>

  <xs:element name="SolidFill">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Fill">
          <xs:attribute name="Color" type="color" use="required"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="GradientFill">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Fill">
          <xs:sequence>
            <xs:element name="Point" maxOccurs="2" minOccurs="2">
              <xs:complexType>
                <xs:attribute name="X" type="xs:double" use="required"/>
                <xs:attribute name="Y" type="xs:double" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="Color1" type="color" use="required"/>
          <xs:attribute name="Color2" type="color" use="required"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="ForeEachParagraph">
    <xs:complexContent>
      <xs:extension base="AbstractParagraph">

        <xs:choice maxOccurs="unbounded">
          <xs:element ref="Paragraph"/>
          <xs:element name="ForEach" type="mstns:ForeEachParagraph" />
        </xs:choice>
        <xs:attribute name="Select" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Paragraph">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="AbstractParagraph">
          <xs:choice maxOccurs="unbounded">
            <xs:element ref="LineBreak"/>
            <xs:element ref="mstns:TextRun"/>
            <xs:element ref="ForEachRun" />
          </xs:choice>

          <xs:attribute name="FontStyle" type="mstns:FontStyle" default="Regular"/>
          <xs:attribute name="EmSize" type="xs:double" default="12"/>
          <xs:attribute name="FontName" type="xs:string"/>

          <xs:attribute name="Color" type="color" default="Black"/>
          <xs:attribute name="Language" type="Language"/>

          <xs:attribute name="Linespacing" default="1" type="xs:double"/>
          <xs:attribute name="BeforeParagraph" type="mstns:Unit" default="0 mm"/>
          <xs:attribute name="AfterParagraph" type="mstns:Unit" default="0 mm"/>
          <xs:attribute name="Alignment" type="mstns:Alignment" default="Near"/>
        </xs:extension>
      </xs:complexContent>

    </xs:complexType>
  </xs:element>


  <xs:element name="LineBreak">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Run">

        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="ForEachRun">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Run">
          <xs:choice maxOccurs="unbounded">
            <xs:element ref="ForEachRun" />
            <xs:element ref="TextRun" />
            <xs:element ref="LineBreak" />
          </xs:choice>
          <xs:attribute name="Select" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="TextRun">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="Run">
          <xs:choice>
            <xs:element name="Text" type="xs:string"/>
            <xs:element name="TextPath" type="xs:string"/>
          </xs:choice>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Run" abstract="true">

    <xs:attribute name="FontStyle" type="mstns:FontStyle"/>
    <xs:attribute name="EmSize" type="xs:double"/>
    <xs:attribute name="FontName" type="xs:string"/>

    <xs:attribute name="Color" type="color"/>
    <xs:attribute name="Language" type="Language"/>


    <xs:attribute name="IsVisible" type="xs:boolean" default="true"/>
    <xs:attribute name="IsVisiblePath" type="xs:string"/>

  </xs:complexType>

  <xs:complexType name="ImageElement">
    <xs:complexContent>
      <xs:extension base="BaseElement">
        <xs:attribute name="ImageLocationPath" type="xs:string"/>
        <xs:attribute name="ImageLocation" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>


</xs:schema>

=== LokiMidgard/nota/input/misc/documents/source/ActionCards/Project.xml
<!-- This sample uses nota.xml from https://github.com/nota-game/nota -->
<!-- If you need xml namespaces in the xpath querys, you need to define those in the project root-->
<Project xmlns="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:nota='http://nota.org/schema/nota'
  xmlns:misc='http://nota.org/schema/misc'
  xmlns:lebewesen="http://nota.org/schema/wesen"
  xmlns:kultur="http://nota.org/schema/kultur"
  xmlns:profession="http://nota.org/schema/profession"
  xmlns:talent="http://nota.org/schema/talent"
  xmlns:fertigkeit="http://nota.org/schema/fertigkeit"
  xmlns:besonderheit="http://nota.org/schema/besonderheit"
  xmlns:aktionen="http://nota.org/schema/kampf/aktionen"
  xmlns:ausstattung="http://nota.org/schema/kampf/ausstattung"
  xsi:schemaLocation="https://raw.githubusercontent.com/LokiMidgard/PdfGenerator/master/PdfGenerator/XMLImport.xsd ../../../../../../PDFGenerator/PDFGenerator/XMLImport.xsd" 
  DefaultLanguage="de-DE">
  <Fonts UseSystemFallback="false" DefaultFont="CMU Serif">
    <Font  FamilyName="CMU Serif" >
      <Regular Path="..\..\..\..\static\fonts\CMU Serif\cmunrm.ttf" />
      <BoldItalic Path="..\..\..\..\static\fonts\CMU Serif\cmunbi.ttf"/>
      <Bold Path="..\..\..\..\static\fonts\CMU Serif\cmunbx.ttf"/>
      <Italic Path="..\..\..\..\static\fonts\CMU Serif\cmunti.ttf" />
    </Font>

    <Font FamilyName="Code200365k">
      <Regular Path="..\..\..\..\static\fonts\Code2003\Code200365k.ttf" />
    </Font>
    <Font FamilyName="BabelStone Roman">
      <Regular Path="..\..\..\..\static\fonts\BabelStone\BabelStoneRoman.ttf" />
    </Font>

     <Font FamilyName="Montreal">
      <Regular Path="..\..\..\..\static\fonts\Montreal\Montreal-Regular.ttf" />
      <Bold Path="..\..\..\..\static\fonts\Montreal\Montreal-Bold.ttf" />
    </Font>

    <Font FamilyName="Quivira">
      <Regular Path="..\..\..\..\static\fonts\Quivira\Quivira.otf" />
    </Font> 
  </Fonts>
  <FallbackFonts>
    <Font FamilyName="Code200365k" />
    <Font FamilyName="BabelStone Roman" />
    <Font FamilyName="Quivira" />
  </FallbackFonts>
  <Templates>
    <Template Context="//nota:Daten/aktionen:Aktionen/aktionen:Aktion" Width="64.9 mm" Height="97 mm" Xslt="PreProcess.xslt">
    <!-- Title-->
      <Text left="10 mm" top="78 mm" width="61 mm" height="5 mm" rotation="-90" >
        <Paragraph  Alignment="Far" EmSize="12" FontStyle="Bold" FontName="Montreal">
          <TextRun>
            <TextPath>Original/aktionen:Aktion/@Name</TextPath>
          </TextRun>
        </Paragraph>
      </Text>
  <!-- Background-->
      <Image left="0 mm" top="0 mm" width="64.9 mm" height="97 mm" ImageLocation="Background-Attack.png" IsVisiblePath="Original/aktionen:Aktion/@Typ='Offensiv'" ZPosition="-2" />
      <Image left="0 mm" top="0 mm" width="64.9 mm" height="97 mm" ImageLocation="Background-Defend.png" IsVisiblePath="Original/aktionen:Aktion/@Typ='Defensiv'" ZPosition="-2" />
      <Image left="0 mm" top="0 mm" width="64.9 mm" height="97 mm" ImageLocation="Background-Seccondär.png" IsVisiblePath="Original/aktionen:Aktion/@Typ='Sekundär'" ZPosition="-2" />
      <Image left="0 mm" top="0 mm" width="64.9 mm" height="97 mm" ImageLocation="Background-Unterstützend.png" IsVisiblePath="Original/aktionen:Aktion/@Typ='Unterstützend'" ZPosition="-2" />

  <!-- AKTION -->
      <Image left="0 mm" 
        top="0 mm" 
        width="64.9 mm" 
        height="97 mm"
        ImageLocation="Aktionen-0-0.png"
        IsVisiblePath="Original/aktionen:Aktion/@Aktionen='0'" ZPosition="-1" />
      <Image left="0 mm" 
        top="0 mm" 
        width="64.9 mm" 
        height="97 mm"
        ImageLocation="Aktionen-0-5.png"
        IsVisiblePath="Original/aktionen:Aktion/@Aktionen='0.5'" ZPosition="-1" />
      <Image left="0 mm" 
        top="0 mm" 
        width="64.9 mm" 
        height="97 mm"
        ImageLocation="Aktionen-1-0.png"
        IsVisiblePath="Original/aktionen:Aktion/@Aktionen='1'" ZPosition="-1" />
      <Image left="0 mm" 
        top="0 mm" 
        width="64.9 mm" 
        height="97 mm"
        ImageLocation="Aktionen-1-5.png"
        IsVisiblePath="Original/aktionen:Aktion/@Aktionen='1.5'" ZPosition="-1" />
      <Image left="0 mm" 
        top="0 mm" 
        width="64.9 mm" 
        height="97 mm"
        ImageLocation="Aktionen-2-0.png"
        IsVisiblePath="Original/aktionen:Aktion/@Aktionen='2'" ZPosition="-1" />


  <!-- KOSTEN-->
      <Text left="10.5 mm" top="9.5 mm" width="4.5 mm" height="4.5 mm">
        <Paragraph  Alignment="Center" EmSize="12" FontStyle="Bold" FontName="Montreal">
          <TextRun>
            <TextPath>Original/aktionen:Aktion/@Kosten</TextPath>
          </TextRun>
        </Paragraph>
      </Text>

  <!-- MODIFIKATION -->
      <Text left="17 mm" top="9 mm" width="40 mm" height="8 mm">
        <Paragraph IsVisiblePath="Malus" Alignment="Center" EmSize="12" FontStyle="Bold"   FontName="Montreal">
          <TextRun FontName="Code200365k">
            <Text>&#10836;</Text>
          </TextRun>
          <TextRun>
            <TextPath>Malus</TextPath>
          </TextRun>
        </Paragraph>
      </Text>
      <Text left="17 mm" top="9 mm" width="40 mm" height="8 mm">
        <Paragraph IsVisiblePath="Bonus" Alignment="Center" EmSize="12" FontStyle="Bold" FontName="Montreal" >
         <TextRun  FontName="Code200365k">
            <Text>&#x2a53;</Text>
          </TextRun>
          <TextRun>
            <TextPath>Bonus</TextPath>
          </TextRun>
        </Paragraph>
      </Text>



  <!-- Haupt text -->
      <Text left="18 mm" top="18 mm" width="37mm" height="60mm" >
        <Paragraph FontStyle="Italic" EmSize="5" IsVisiblePath="Original/aktionen:Aktion/aktionen:Beschreibung" FontName="CMU Serif">
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:Beschreibung</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:Bedingung" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun  FontName="Montreal">
            <Text>Bedingung</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:Bedingung" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:Bedingung</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:InstantEffekt" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun FontName="Montreal">
            <Text>Augenblicklicher Effekt</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:InstantEffekt" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:InstantEffekt</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:GarantierterEffekt" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun FontName="Montreal">
            <Text>Garantierter Effekt</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:GarantierterEffekt" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:GarantierterEffekt</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:OffensivErfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun FontName="Montreal">
            <Text>Offensiv Erfolg</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:OffensivErfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:OffensivErfolg</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:DefensivErfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun FontName="Montreal">
            <Text>Defensiver Erfolg</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:DefensivErfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:DefensivErfolg</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:SekundärErfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun FontName="Montreal">
            <Text>Sekundeärer Erfolg</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:SekundärErfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:SekundärErfolg</TextPath>
          </TextRun>
        </Paragraph>

        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:OffensivMiserfolg" BeforeParagraph="4mm" AfterParagraph="2mm" FontStyle="Bold" EmSize="7" >
          <TextRun FontName="Montreal">
            <Text>Offensiver Misserfolg</Text>
          </TextRun>
        </Paragraph>
        <Paragraph IsVisiblePath="Original/aktionen:Aktion/aktionen:OffensivMiserfolg" BeforeParagraph="1mm" AfterParagraph="0mm" EmSize="6" >
          <TextRun>
            <TextPath>Original/aktionen:Aktion/aktionen:OffensivMiserfolg</TextPath>
          </TextRun>
        </Paragraph>
